import * as jose from "jose";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  generatePreferencesUrl,
  generateUnsubscribeToken,
  generateUnsubscribeUrl,
  verifyUnsubscribeToken,
} from "../index";

const TEST_SECRET = "test-secret-for-unsubscribe";

// Cross-compat token: generated by apps/web on 2026-06-11T00:00:00Z with
// UNSUBSCRIBE_SECRET=cross-compat-fixed-secret, payload {cid:"cid-1",oid:"oid-1",tid:"tid-1"}
// It expires 2026-09-10, so the test that uses it pins the clock; without the
// pin this file starts failing on its own.
const CROSS_COMPAT_TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJjaWQiOiJjaWQtMSIsIm9pZCI6Im9pZC0xIiwidHlwZSI6InVuc3ViIiwidGlkIjoidGlkLTEiLCJpYXQiOjE3ODExMzYwMDAsImV4cCI6MTc4ODkxMjAwMH0.bRwVQLZcgcNcbHIikKkXF9m8qwRffiY13H2PGjtV25w";

// Every entry point reads process.env at call time, so the module is imported
// once at the top and vi.stubEnv alone decides what each test sees. Do not
// reintroduce per-test `await import("../index")`: that puts a cold module
// graph load inside the 5s test timeout, which is what made this file flaky
// under parallel runs.
describe("Unsubscribe Token", () => {
  beforeEach(() => {
    vi.stubEnv("UNSUBSCRIBE_SECRET", TEST_SECRET);
  });

  afterEach(() => {
    vi.unstubAllEnvs();
    vi.useRealTimers();
  });

  describe("getSecret behavior", () => {
    it("should generate and verify tokens when UNSUBSCRIBE_SECRET is set", async () => {
      const token = await generateUnsubscribeToken(
        "contact-123",
        "org-456",
        "topic-789"
      );

      const payload = await verifyUnsubscribeToken(token);

      expect(payload).not.toBeNull();
      expect(payload?.cid).toBe("contact-123");
      expect(payload?.oid).toBe("org-456");
      expect(payload?.tid).toBe("topic-789");
      expect(payload?.type).toBe("unsub");
    });

    it("should throw in production when UNSUBSCRIBE_SECRET is not set (NODE_ENV=production)", async () => {
      vi.stubEnv("NODE_ENV", "production");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");

      await expect(
        generateUnsubscribeToken("contact-123", "org-456")
      ).rejects.toThrow(
        "UNSUBSCRIBE_SECRET environment variable is required in production"
      );
    });

    it("should throw in production when UNSUBSCRIBE_SECRET is not set (VERCEL_ENV=production)", async () => {
      vi.stubEnv("VERCEL_ENV", "production");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");

      await expect(
        generateUnsubscribeToken("contact-123", "org-456")
      ).rejects.toThrow(
        "UNSUBSCRIBE_SECRET environment variable is required in production"
      );
    });

    it("should throw in production when UNSUBSCRIBE_SECRET is not set (AWS_LAMBDA_FUNCTION_NAME set)", async () => {
      vi.stubEnv("AWS_LAMBDA_FUNCTION_NAME", "my-function");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");

      await expect(
        generateUnsubscribeToken("contact-123", "org-456")
      ).rejects.toThrow(
        "UNSUBSCRIBE_SECRET environment variable is required in production"
      );
    });

    it("should use fallback secret in development when UNSUBSCRIBE_SECRET is not set", async () => {
      vi.stubEnv("NODE_ENV", "development");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");

      const token = await generateUnsubscribeToken("contact-123", "org-456");

      expect(token).toBeDefined();
      expect(typeof token).toBe("string");

      const payload = await verifyUnsubscribeToken(token);
      expect(payload).not.toBeNull();
      expect(payload?.cid).toBe("contact-123");
    });

    it("should not accept a dev-secret token once the secret is configured", async () => {
      vi.stubEnv("NODE_ENV", "development");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");

      const devToken = await generateUnsubscribeToken("contact-123", "org-456");

      vi.stubEnv("UNSUBSCRIBE_SECRET", TEST_SECRET);

      expect(await verifyUnsubscribeToken(devToken)).toBeNull();
    });
  });

  describe("generateUnsubscribeToken", () => {
    it("should generate a valid JWT token", async () => {
      const token = await generateUnsubscribeToken("contact-123", "org-456");

      expect(token).toBeDefined();
      expect(typeof token).toBe("string");
      expect(token.split(".")).toHaveLength(3);
    });

    it("should generate token without topic ID", async () => {
      const token = await generateUnsubscribeToken("contact-123", "org-456");
      const payload = await verifyUnsubscribeToken(token);

      expect(payload).not.toBeNull();
      expect(payload?.tid).toBeUndefined();
    });

    it("should set a 90-day expiry", async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2026-06-11T00:00:00Z"));

      const token = await generateUnsubscribeToken("contact-123", "org-456");
      const { iat, exp } = jose.decodeJwt(token);

      expect(iat).toBe(1_781_136_000);
      expect((exp as number) - (iat as number)).toBe(90 * 24 * 60 * 60);
    });

    it("should produce a token that no longer verifies once the 90-day window closes", async () => {
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2026-06-11T00:00:00Z"));

      const token = await generateUnsubscribeToken("contact-123", "org-456");
      expect(await verifyUnsubscribeToken(token)).not.toBeNull();

      // One day past the 90-day window
      vi.setSystemTime(new Date("2026-09-11T00:00:00Z"));

      const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
      expect(await verifyUnsubscribeToken(token, log)).toBeNull();
      expect(log.info).toHaveBeenCalledWith("Unsubscribe: token expired");
    });
  });

  describe("verifyUnsubscribeToken", () => {
    it("should return null for invalid token", async () => {
      const payload = await verifyUnsubscribeToken("invalid-token");
      expect(payload).toBeNull();
    });

    it("should return null for tampered token (flipped signature character)", async () => {
      const token = await generateUnsubscribeToken(
        "contact-123",
        "org-456",
        "topic-789"
      );
      const parts = token.split(".");
      const [header, body, sig] = parts as [string, string, string];
      // Flip one character in the signature
      const tamperedSig =
        sig[0] === "a" ? `b${sig.slice(1)}` : `a${sig.slice(1)}`;
      const tamperedToken = `${header}.${body}.${tamperedSig}`;

      const payload = await verifyUnsubscribeToken(tamperedToken);
      expect(payload).toBeNull();
    });

    it("should return null for a token whose claims were swapped for another contact", async () => {
      const token = await generateUnsubscribeToken("contact-123", "org-456");
      const [header, , sig] = token.split(".") as [string, string, string];
      const forgedBody = Buffer.from(
        JSON.stringify({
          cid: "victim-999",
          exp: Math.floor(Date.now() / 1000) + 3600,
          oid: "org-456",
          type: "unsub",
        })
      ).toString("base64url");

      const payload = await verifyUnsubscribeToken(
        `${header}.${forgedBody}.${sig}`
      );
      expect(payload).toBeNull();
    });

    it("should return null for token signed with different secret", async () => {
      const token = await generateUnsubscribeToken("contact-123", "org-456");

      vi.stubEnv("UNSUBSCRIBE_SECRET", "different-secret");

      const payload = await verifyUnsubscribeToken(token);
      expect(payload).toBeNull();
    });

    it("should reject an unsigned (alg: none) token", async () => {
      const token = await new jose.UnsecuredJWT({
        cid: "contact-123",
        oid: "org-456",
        type: "unsub",
      })
        .setIssuedAt()
        .setExpirationTime("90d")
        .encode();

      expect(await verifyUnsubscribeToken(token)).toBeNull();
    });

    it("should reject a correctly signed token that is not an unsubscribe token", async () => {
      // Signature is valid — only the `type` marker is wrong. This is the
      // branch that stops a confirmation/preferences token from being replayed
      // against the unsubscribe endpoint.
      const token = await new jose.SignJWT({
        cid: "contact-123",
        oid: "org-456",
        type: "confirm",
      })
        .setProtectedHeader({ alg: "HS256" })
        .setIssuedAt()
        .setExpirationTime("90d")
        .sign(new TextEncoder().encode(TEST_SECRET));

      const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };

      expect(await verifyUnsubscribeToken(token, log)).toBeNull();
      expect(log.warn).toHaveBeenCalledWith(
        "Unsubscribe: invalid token payload structure"
      );
    });

    it("should reject a correctly signed token that is missing cid/oid", async () => {
      const token = await new jose.SignJWT({ type: "unsub" })
        .setProtectedHeader({ alg: "HS256" })
        .setIssuedAt()
        .setExpirationTime("90d")
        .sign(new TextEncoder().encode(TEST_SECRET));

      const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };

      expect(await verifyUnsubscribeToken(token, log)).toBeNull();
      expect(log.warn).toHaveBeenCalledWith(
        "Unsubscribe: invalid token payload structure"
      );
    });

    it("should drop a non-string tid rather than passing it through", async () => {
      const token = await new jose.SignJWT({
        cid: "contact-123",
        oid: "org-456",
        tid: 42,
        type: "unsub",
      })
        .setProtectedHeader({ alg: "HS256" })
        .setIssuedAt()
        .setExpirationTime("90d")
        .sign(new TextEncoder().encode(TEST_SECRET));

      const payload = await verifyUnsubscribeToken(token);

      expect(payload).not.toBeNull();
      expect(payload?.tid).toBeUndefined();
    });

    it("should not throw when log param is omitted", async () => {
      const token = await new jose.SignJWT({ type: "unsub" })
        .setProtectedHeader({ alg: "HS256" })
        .setIssuedAt()
        .setExpirationTime("90d")
        .sign(new TextEncoder().encode(TEST_SECRET));

      // Exercises the same `log?.warn` / `log?.error` branches as above with no
      // logger supplied — the optional-chaining must not blow up.
      expect(await verifyUnsubscribeToken(token)).toBeNull();
      expect(await verifyUnsubscribeToken("not.a.jwt")).toBeNull();
    });

    // A mangled link is recipient input, not a server fault. Reporting it at
    // error level paged Sentry (JWSInvalid: Invalid Compact JWS) for a
    // truncated URL someone pasted into a browser.
    it.each([
      [
        "a truncated link (not three segments)",
        async () => "eyJhbGciOiJIUzI1NiJ9",
      ],
      [
        "a tampered signature",
        async () => {
          const [header, body] = (
            await generateUnsubscribeToken("contact-123", "org-456")
          ).split(".");
          return `${header}.${body}.AAAA`;
        },
      ],
      [
        "an unsigned (alg: none) token",
        () =>
          new jose.UnsecuredJWT({ cid: "c", oid: "o", type: "unsub" }).encode(),
      ],
    ])("warns rather than errors for %s", async (_label, makeToken) => {
      const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };

      expect(await verifyUnsubscribeToken(await makeToken(), log)).toBeNull();
      expect(log.warn).toHaveBeenCalledWith("Unsubscribe: invalid token");
      expect(log.error).not.toHaveBeenCalled();
    });

    it("still reports a missing production secret as an error", async () => {
      const token = await generateUnsubscribeToken("contact-123", "org-456");
      vi.stubEnv("NODE_ENV", "production");
      vi.stubEnv("UNSUBSCRIBE_SECRET", "");
      const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };

      expect(await verifyUnsubscribeToken(token, log)).toBeNull();
      expect(log.error).toHaveBeenCalledWith(
        "Unsubscribe: token verification failed",
        expect.objectContaining({
          message: expect.stringContaining("UNSUBSCRIBE_SECRET"),
        })
      );
    });

    it("cross-compat: token generated by old web implementation verifies correctly", async () => {
      vi.stubEnv("UNSUBSCRIBE_SECRET", "cross-compat-fixed-secret");
      // Pin time to 2026-06-12 — one day after capture, inside the 90-day window
      vi.useFakeTimers();
      vi.setSystemTime(new Date("2026-06-12T00:00:00Z"));

      const payload = await verifyUnsubscribeToken(CROSS_COMPAT_TOKEN);

      expect(payload).not.toBeNull();
      expect(payload?.cid).toBe("cid-1");
      expect(payload?.oid).toBe("oid-1");
      expect(payload?.tid).toBe("tid-1");
      expect(payload?.type).toBe("unsub");
    });
  });

  // Regression guard for the self-hosted wrong-domain bug: these URLs are
  // embedded in mail sent to real recipients, so a silent fallback to the Wraps
  // platform sends a self-hosted customer's contacts to a server that has never
  // seen their token. Failing the send is the lesser harm.
  describe("generatePreferencesUrl", () => {
    it("uses the configured dashboard URL", async () => {
      vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://mail.customer.test");

      const url = await generatePreferencesUrl("contact-123", "org-456");

      expect(url).toMatch(/^https:\/\/mail\.customer\.test\/preferences\/.+/);
    });

    it("embeds a token that verifies back to the same contact", async () => {
      vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://mail.customer.test");

      const url = await generatePreferencesUrl("contact-123", "org-456");
      const token = url.split("/preferences/")[1] as string;

      const payload = await verifyUnsubscribeToken(token);
      expect(payload?.cid).toBe("contact-123");
      expect(payload?.oid).toBe("org-456");
    });

    it("throws instead of falling back to the Wraps platform when no URL is configured", async () => {
      vi.stubEnv("NEXT_PUBLIC_APP_URL", "");
      vi.stubEnv("BETTER_AUTH_URL", "");
      vi.stubEnv("APP_BASE_URL", "");

      const result = await generatePreferencesUrl(
        "contact-123",
        "org-456"
      ).then(
        (url) => ({ ok: true as const, url }),
        (error: Error) => ({ ok: false as const, message: error.message })
      );

      expect(result.ok).toBe(false);
      if (result.ok) {
        return;
      }
      expect(result.message).toMatch(/NEXT_PUBLIC_APP_URL/);
      expect(result.message).not.toContain("app.wraps.dev");
    });

    it("strips a trailing slash from the configured URL", async () => {
      vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://x.test/");

      const url = await generatePreferencesUrl("contact-123", "org-456");

      expect(url).not.toContain("//preferences");
      expect(url).toMatch(/^https:\/\/x\.test\/preferences\/.+/);
    });
  });

  describe("generateUnsubscribeUrl", () => {
    it("uses the configured API URL", async () => {
      vi.stubEnv("API_BASE_URL", "https://api.customer.test");

      const url = await generateUnsubscribeUrl("contact-123", "org-456");

      expect(url).toMatch(/^https:\/\/api\.customer\.test\/unsubscribe\/.+/);
    });

    it("embeds a token carrying the topic when one is given", async () => {
      vi.stubEnv("API_BASE_URL", "https://api.customer.test");

      const url = await generateUnsubscribeUrl(
        "contact-123",
        "org-456",
        "topic-789"
      );
      const token = url.split("/unsubscribe/")[1] as string;

      const payload = await verifyUnsubscribeToken(token);
      expect(payload?.cid).toBe("contact-123");
      expect(payload?.tid).toBe("topic-789");
    });

    it("throws instead of falling back to the Wraps platform when no URL is configured", async () => {
      vi.stubEnv("API_BASE_URL", "");
      vi.stubEnv("NEXT_PUBLIC_API_URL", "");

      const result = await generateUnsubscribeUrl(
        "contact-123",
        "org-456"
      ).then(
        (url) => ({ ok: true as const, url }),
        (error: Error) => ({ ok: false as const, message: error.message })
      );

      expect(result.ok).toBe(false);
      if (result.ok) {
        return;
      }
      expect(result.message).toMatch(/API_BASE_URL/);
      expect(result.message).not.toContain("api.wraps.dev");
    });
  });
});
