import { SectionKicker } from "@/app/landing/components/section-kicker";

export function MarketingMeasurementSection() {
  return (
    <section className="py-16 sm:py-24">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="grid items-start gap-12 lg:grid-cols-2 lg:gap-16">
          <div>
            <SectionKicker>Reporting</SectionKicker>
            <h2 className="mb-3 font-bold text-3xl tracking-tight sm:text-4xl">
              An open rate you can actually defend in a meeting.
            </h2>
            <p className="mb-5 text-lg text-muted-foreground">
              Every broadcast gets a Sankey diagram tracing sent → delivered →
              opened → clicked, with clicks broken out per destination URL, and
              a funnel showing the conversion rate at each step.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Opens generated by security scanners and inbox prefetchers are
              filtered out of engagement metrics. The number that goes in the
              deck is lower than the vanity version and survives someone asking
              where it came from.
            </p>
          </div>

          <div className="space-y-4">
            {[
              {
                stat: "Per-URL",
                title: "Click breakdown",
                body: "Which link in the email did the work, not just whether somebody clicked something.",
              },
              {
                stat: "Ranked",
                title: "Subject line performance",
                body: "Top performers sorted by engagement across sends, so the next subject line is an informed guess.",
              },
              {
                stat: "Per-message",
                title: "Event timeline",
                body: "Search to one send and read every event it produced, in order — useful when one customer swears they never got it.",
              },
            ].map(({ stat, title, body }) => (
              <div
                className="rounded-xl border border-border bg-card/60 p-5"
                key={title}
              >
                <div className="mb-2 font-mono text-[11px] text-orange-500 uppercase tracking-[0.14em]">
                  {stat}
                </div>
                <h3 className="mb-1.5 font-medium text-base tracking-tight">
                  {title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
