"use client";

import {
  CodeBlock,
  CodeBlockBody,
  CodeBlockContent,
  CodeBlockCopyButton,
  CodeBlockItem,
} from "@/components/ui/shadcn-io/code-block";

const templateCode = `// wraps/templates/welcome.tsx
import { Html, Head, Body, Container, Text, Button } from '@react-email/components';

export const subject = 'Welcome, {{name}}!';
export const emailType = 'transactional';
export const previewText = 'Your account is ready';

export default function Welcome(props: { name: string; dashboardUrl: string }) {
  return (
    <Html>
      <Head />
      <Body>
        <Container>
          <Text>Hi {props.name},</Text>
          <Text>Your account is ready. Let's get you set up.</Text>
          <Button href={props.dashboardUrl}>Open Dashboard</Button>
        </Container>
      </Body>
    </Html>
  );
}`;

const workflowCode = `// wraps/workflows/welcome-series.ts
import { defineWorkflow, sendEmail, delay, condition } from '@wraps.dev/client';

export default defineWorkflow({
  name: 'Welcome Series',
  trigger: { type: 'contact_created' },
  steps: [
    sendEmail('welcome', { template: 'welcome-email' }),
    delay('wait-1-day', { days: 1 }),
    condition('setup-complete', {
      field: 'contact.hasCompletedSetup',
      operator: 'equals',
      value: true,
      branches: {
        yes: [sendEmail('success', { template: 'success-story' })],
        no: [sendEmail('nudge', { template: 'setup-nudge' })],
      },
    }),
  ],
});`;

const templateData = [
  {
    language: "tsx",
    filename: "wraps/templates/welcome.tsx",
    code: templateCode,
  },
];

const workflowData = [
  {
    language: "typescript",
    filename: "wraps/workflows/welcome-series.ts",
    code: workflowCode,
  },
];

export function CodeFirstSection() {
  return (
    <section className="py-24" id="code-first">
      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="mb-12 animate-fade-in-up">
          <h2 className="mb-4 font-bold text-3xl tracking-tight md:text-4xl">
            Write it. Review it. Ship it. Or let an agent do it for you.
          </h2>
          <p className="max-w-3xl text-lg text-muted-foreground">
            Your email infrastructure is TypeScript and React. The same code
            your team writes, an AI agent can generate. Both go through PRs.
            Both deploy the same way.
          </p>
        </div>

        {/* Code examples */}
        <div className="space-y-10 animate-fade-in-up animation-delay-100">
          {/* Template example */}
          <div>
            <CodeBlock data={templateData} defaultValue="tsx">
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem key={item.language} value={item.language}>
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                    <CodeBlockCopyButton />
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
            <p className="mt-3 text-sm text-muted-foreground">
              Typed props. Component composition. Written by your team or
              generated by an agent. Reviewed in the same PR as the feature it
              supports.
            </p>
          </div>

          {/* Workflow example */}
          <div>
            <CodeBlock data={workflowData} defaultValue="typescript">
              <CodeBlockBody>
                {(item) => (
                  <CodeBlockItem key={item.language} value={item.language}>
                    <CodeBlockContent language={item.language}>
                      {item.code}
                    </CodeBlockContent>
                    <CodeBlockCopyButton />
                  </CodeBlockItem>
                )}
              </CodeBlockBody>
            </CodeBlock>
            <p className="mt-3 text-sm text-muted-foreground">
              Delays. Conditions. Branching. Ship your onboarding sequence in
              the same PR as your signup flow.
            </p>
          </div>
        </div>

        {/* Section closer */}
        <div className="mt-12 animate-fade-in-up animation-delay-200">
          <p className="text-lg text-muted-foreground">
            The same template a developer writes as React, a marketer generates
            with AI. The same workflow defined in TypeScript, an AI agent builds
            from a prompt. One system. Two ways to work.
          </p>
          <a
            className="mt-4 inline-flex items-center text-sm font-medium text-orange-500 hover:text-orange-600"
            href="/docs/quickstart/email"
          >
            Read the docs →
          </a>
        </div>
      </div>
    </section>
  );
}
