import {
  CASCADE_ENGAGEMENT_FIELD,
  type CanvasViewport,
  type CascadeChannelConfig,
  type TriggerConfig,
  type Workflow,
  type WorkflowStep,
  type WorkflowStepConfig,
  type WorkflowStepType,
  type WorkflowTransition,
  type WorkflowTriggerType,
} from "@wraps/db";
import type {
  Connection,
  Edge,
  Node,
  OnConnect,
  OnEdgesChange,
  OnNodesChange,
} from "@xyflow/react";
import {
  addEdge,
  applyEdgeChanges,
  applyNodeChanges,
  reconnectEdge,
} from "@xyflow/react";
import { temporal } from "zundo";
import { create, useStore } from "zustand";
import {
  type ValidationError,
  type ValidationResult,
  validateCascadeChannels,
  validateAutomation,
} from "@/lib/automation-validation";
import type { NodePaletteType } from "./node-palette";

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Canvas node type = all step types + the "cascade" virtual node.
 * Cascade exists only on the canvas and is expanded to primitives on save.
 */
export type CanvasNodeType = WorkflowStepType | "cascade";

export type WorkflowNodeData = {
  stepId: string;
  type: CanvasNodeType;
  name: string;
  config: WorkflowStepConfig;
  isValid: boolean;
  errorMessage?: string;
  // Cascade channels (only present on cascade nodes)
  cascadeChannels?: CascadeChannelConfig[];
};

export type WorkflowNode = Node<WorkflowNodeData>;
export type WorkflowEdge = Edge<{ label?: string }>;

// ═══════════════════════════════════════════════════════════════════════════
// STORE
// ═══════════════════════════════════════════════════════════════════════════

type CascadeMapping = {
  firstStepId: string;
  engagedConditionIds: string[];
  lastSendId: string;
  /** ID of the "engaged exit" node, for routing engaged edges */
  engagedExitId: string;
  /** All primitive step IDs generated by this cascade node */
  allStepIds: string[];
};

type WorkflowStoreState = {
  // Workflow metadata
  workflow: Workflow | null;
  isDirty: boolean;
  isSaving: boolean;

  // React Flow state
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  canvasViewport: CanvasViewport;

  // UI state
  selectedNodeId: string | null;
  settingsPanelOpen: boolean;

  // Validation state
  validationResult: ValidationResult | null;

  // Actions
  setWorkflow: (workflow: Workflow) => void;
  setNodes: (nodes: WorkflowNode[]) => void;
  setEdges: (edges: WorkflowEdge[]) => void;
  onNodesChange: OnNodesChange<WorkflowNode>;
  onEdgesChange: OnEdgesChange<WorkflowEdge>;
  onConnect: OnConnect;
  onReconnect: (oldEdge: WorkflowEdge, newConnection: Connection) => void;

  addNode: (
    type: NodePaletteType,
    position: { x: number; y: number },
    config?: Partial<WorkflowStepConfig>
  ) => string;
  updateNodeConfig: (
    nodeId: string,
    config: Partial<WorkflowStepConfig>
  ) => void;
  updateNodeName: (nodeId: string, name: string) => void;
  deleteNode: (nodeId: string) => void;

  // Cascade channel actions
  updateCascadeChannels: (
    nodeId: string,
    channels: CascadeChannelConfig[]
  ) => void;

  selectNode: (nodeId: string | null) => void;
  toggleSettingsPanel: () => void;
  setSettingsPanelOpen: (open: boolean) => void;
  setCanvasViewport: (viewport: CanvasViewport) => void;

  // Workflow actions
  updateWorkflowSettings: (settings: {
    name?: string;
    description?: string;
    triggerType?: WorkflowTriggerType;
    triggerConfig?: TriggerConfig;
    allowReentry?: boolean;
    reentryDelaySeconds?: number | null;
  }) => void;

  // Serialization
  getWorkflowDefinition: () => {
    steps: WorkflowStep[];
    transitions: WorkflowTransition[];
    canvasViewport: CanvasViewport;
  };

  setIsSaving: (isSaving: boolean) => void;
  markClean: () => void;

  // Update workflow after save without touching nodes/edges (avoids re-triggering dirty state)
  updateWorkflowAfterSave: (workflow: Workflow) => void;

  // Validation
  runValidation: () => ValidationResult;

  // AI Flow Designer
  applyAIFlow: (
    steps: WorkflowStep[],
    transitions: WorkflowTransition[]
  ) => void;
};

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Convert workflow steps to React Flow nodes.
 * Collapses cascade primitive steps (identified by cascadeGroupId) back into
 * single cascade nodes using the stored cascadeChannels metadata.
 */
function stepsToNodes(steps: WorkflowStep[]): WorkflowNode[] {
  // Identify cascade groups from steps
  const cascadeGroupIds = new Set<string>();
  for (const step of steps) {
    if (step.cascadeGroupId) {
      cascadeGroupIds.add(step.cascadeGroupId);
    }
  }

  // If no cascade groups, return flat nodes
  if (cascadeGroupIds.size === 0) {
    return steps.map((step) => ({
      id: step.id,
      type: step.type,
      position: step.position,
      data: {
        stepId: step.id,
        type: step.type,
        name: step.name,
        config: step.config,
        isValid: true,
      },
    }));
  }

  const allNodes: WorkflowNode[] = [];

  // Process each cascade group → collapse into a single cascade node
  for (const groupId of cascadeGroupIds) {
    const groupSteps = steps.filter((s) => s.cascadeGroupId === groupId);
    if (groupSteps.length === 0) continue;

    // Look for cascadeChannels metadata on the first step
    const stepWithMeta = groupSteps.find((s) => s.cascadeChannels);
    const channels: CascadeChannelConfig[] =
      stepWithMeta?.cascadeChannels ??
      reconstructChannelsFromPrimitives(groupSteps);

    // Use the first step's position for the cascade node
    const firstStep = groupSteps.reduce((a, b) =>
      a.position.y < b.position.y ? a : b
    );

    const cascadeNode: WorkflowNode = {
      id: groupId,
      type: "cascade",
      position: firstStep.position,
      data: {
        stepId: groupId,
        type: "cascade",
        name: "Cascade",
        config: { type: "exit" } as WorkflowStepConfig, // placeholder
        isValid: true,
        cascadeChannels: channels,
      },
    };
    allNodes.push(cascadeNode);
  }

  // Add non-cascade nodes
  for (const step of steps) {
    if (!step.cascadeGroupId) {
      allNodes.push({
        id: step.id,
        type: step.type,
        position: step.position,
        data: {
          stepId: step.id,
          type: step.type,
          name: step.name,
          config: step.config,
          isValid: true,
        },
      });
    }
  }

  return allNodes;
}

/**
 * Reconstruct cascade channels from primitive steps when cascadeChannels
 * metadata is not available (backward compatibility with old data).
 */
function reconstructChannelsFromPrimitives(
  groupSteps: WorkflowStep[]
): CascadeChannelConfig[] {
  const channels: CascadeChannelConfig[] = [];

  // Find send steps (these represent channels)
  const sendSteps = groupSteps.filter(
    (s) => s.type === "send_email" || s.type === "send_sms"
  );

  // Find wait steps for engagement duration
  const waitSteps = groupSteps.filter(
    (s) => s.type === "wait_for_email_engagement"
  );

  for (let i = 0; i < sendSteps.length; i++) {
    const sendStep = sendSteps[i];
    const isLast = i === sendSteps.length - 1;

    if (sendStep.type === "send_email") {
      const templateId =
        sendStep.config.type === "send_email" ? sendStep.config.templateId : "";
      // Find the corresponding wait step (by position order)
      const waitStep = waitSteps[i] || waitSteps[0];
      const waitDuration =
        waitStep?.config.type === "wait_for_email_engagement"
          ? waitStep.config.timeoutSeconds
          : undefined;

      channels.push({
        type: "email",
        templateId: templateId || undefined,
        engagement: "opened",
        waitDuration: isLast ? undefined : (waitDuration ?? 259_200),
      });
    } else if (sendStep.type === "send_sms") {
      const body =
        sendStep.config.type === "send_sms" ? sendStep.config.body : undefined;
      channels.push({
        type: "sms",
        body: body || undefined,
      });
    }
  }

  // Fallback: if no channels found, return default
  if (channels.length === 0) {
    return [
      {
        type: "email",
        engagement: "opened",
        waitDuration: 259_200,
      },
      { type: "sms" },
    ];
  }

  return channels;
}

/**
 * Convert workflow transitions to React Flow edges.
 * Filters out internal cascade transitions (those between primitives in a group)
 * and maps external transitions to/from cascade nodes.
 */
function transitionsToEdges(
  transitions: WorkflowTransition[],
  steps: WorkflowStep[]
): WorkflowEdge[] {
  // Build cascade group membership map
  const stepToGroup = new Map<string, string>();
  const groupFirstStep = new Map<string, string>();
  const groupEngagedExits = new Map<string, string[]>();
  const groupLastSend = new Map<string, string>();

  for (const step of steps) {
    if (step.cascadeGroupId) {
      stepToGroup.set(step.id, step.cascadeGroupId);
    }
  }

  // Identify first send, engaged exits, and last send per group
  for (const groupId of new Set(stepToGroup.values())) {
    const groupSteps = steps.filter((s) => s.cascadeGroupId === groupId);
    const sendSteps = groupSteps.filter(
      (s) => s.type === "send_email" || s.type === "send_sms"
    );
    const exitSteps = groupSteps.filter((s) => s.type === "exit");

    if (sendSteps.length > 0) {
      // First send step (entry point)
      const firstSend = sendSteps.reduce((a, b) =>
        a.position.y < b.position.y ? a : b
      );
      groupFirstStep.set(groupId, firstSend.id);

      // Last send step (exhausted endpoint)
      const lastSend = sendSteps.reduce((a, b) =>
        a.position.y > b.position.y ? a : b
      );
      groupLastSend.set(groupId, lastSend.id);
    }

    // Exit steps represent "engaged" exits
    if (exitSteps.length > 0) {
      groupEngagedExits.set(
        groupId,
        exitSteps.map((s) => s.id)
      );
    }
  }

  const edges: WorkflowEdge[] = [];

  for (const transition of transitions) {
    const fromGroup = stepToGroup.get(transition.fromStepId);
    const toGroup = stepToGroup.get(transition.toStepId);

    // Skip purely internal cascade transitions
    if (fromGroup && toGroup && fromGroup === toGroup) {
      continue;
    }

    // Map legacy "none" branch to "timeout" handle ID
    let branch = transition.condition?.branch as string | undefined;
    if (branch === "none") branch = "timeout";

    let source = transition.fromStepId;
    let target = transition.toStepId;
    let sourceHandle = branch;

    // Map from cascade primitive → cascade node handle
    if (fromGroup) {
      source = fromGroup;
      const engagedExits = groupEngagedExits.get(fromGroup) || [];
      if (engagedExits.includes(transition.fromStepId)) {
        // Edge from an engaged exit → map to "engaged" handle
        sourceHandle = "engaged";
      } else if (transition.fromStepId === groupLastSend.get(fromGroup)) {
        // Edge from last send → map to "exhausted" handle
        sourceHandle = "exhausted";
      }
    }

    // Map to cascade primitive → cascade node
    if (toGroup) {
      target = toGroup;
    }

    edges.push({
      id: transition.id,
      source,
      target,
      sourceHandle,
      data: { label: sourceHandle },
    });
  }

  return edges;
}

/**
 * Expand a cascade node into primitive workflow steps and transitions.
 */
function expandCascadeNode(node: WorkflowNode): {
  steps: WorkflowStep[];
  transitions: WorkflowTransition[];
  /** ID of the first send step (entry point for incoming edges) */
  firstStepId: string;
  /** IDs of condition steps whose "yes" branch = "engaged" */
  engagedConditionIds: string[];
  /** ID of the last send step (source for "exhausted" edges) */
  lastSendId: string;
  /** ID of the "engaged exit" node, if one was created */
  engagedExitId: string;
} {
  const channels = node.data.cascadeChannels ?? [];
  const cascadeGroupId = node.id;
  const steps: WorkflowStep[] = [];
  const transitions: WorkflowTransition[] = [];
  const engagedConditionIds: string[] = [];
  let firstStepId = "";
  let lastSendId = "";
  let engagedExitId = "";

  // Track the previous step ID and whether it was a condition step
  let prevStepId = "";
  let prevIsCondition = false;

  for (let i = 0; i < channels.length; i++) {
    const channel = channels[i];
    const isLast = i === channels.length - 1;
    const isFirst = i === 0;

    // Create send step with deterministic ID
    const sendId = `${cascadeGroupId}-send-${i}`;
    const sendStep: WorkflowStep = {
      id: sendId,
      type: channel.type === "email" ? "send_email" : "send_sms",
      name:
        channel.type === "email"
          ? `Send Email ${channels.filter((c, j) => c.type === "email" && j <= i).length}`
          : `Send SMS ${channels.filter((c, j) => c.type === "sms" && j <= i).length}`,
      position: { x: node.position.x, y: node.position.y + i * 200 },
      config:
        channel.type === "email"
          ? ({
              type: "send_email",
              templateId: channel.templateId || "",
            } as WorkflowStepConfig)
          : ({
              type: "send_sms",
              body: channel.body,
            } as WorkflowStepConfig),
      cascadeGroupId,
      // Store cascade metadata on the first step for reconstruction
      ...(isFirst ? { cascadeChannels: channels } : {}),
    };
    steps.push(sendStep);

    if (isFirst) firstStepId = sendId;
    lastSendId = sendId;

    // Chain from previous step
    if (prevStepId) {
      transitions.push({
        id: `${cascadeGroupId}-tr-${prevStepId}-${sendId}`,
        fromStepId: prevStepId,
        toStepId: sendId,
        // Only condition steps use branch-based transitions ("no" = not engaged).
        // SMS send steps use branchless transitions so the backend's
        // processNextStep fallback routing (`!t.condition`) picks them up.
        condition: prevIsCondition ? { branch: "no" } : undefined,
      });
    }

    // If not last channel and email type, add wait + condition
    if (!isLast && channel.type === "email" && channel.waitDuration) {
      const waitId = `${cascadeGroupId}-wait-${i}`;
      const conditionId = `${cascadeGroupId}-cond-${i}`;

      // Wait for engagement step
      steps.push({
        id: waitId,
        type: "wait_for_email_engagement",
        name: "Wait for Engagement",
        position: {
          x: node.position.x,
          y: node.position.y + i * 200 + 80,
        },
        config: {
          type: "wait_for_email_engagement",
          timeoutSeconds: channel.waitDuration,
        } as WorkflowStepConfig,
        cascadeGroupId,
      });

      // Condition step
      steps.push({
        id: conditionId,
        type: "condition",
        name: "Engaged?",
        position: {
          x: node.position.x,
          y: node.position.y + i * 200 + 140,
        },
        config: {
          type: "condition",
          field: CASCADE_ENGAGEMENT_FIELD,
          operator: "equals",
          value: "true",
        } as WorkflowStepConfig,
        cascadeGroupId,
      });

      // send → wait
      transitions.push({
        id: `${cascadeGroupId}-tr-${sendId}-${waitId}`,
        fromStepId: sendId,
        toStepId: waitId,
      });

      // wait → condition (timeout)
      transitions.push({
        id: `${cascadeGroupId}-tr-${waitId}-${conditionId}`,
        fromStepId: waitId,
        toStepId: conditionId,
        condition: { branch: "timeout" },
      });

      engagedConditionIds.push(conditionId);
      prevStepId = conditionId;
      prevIsCondition = true;
    } else if (!isLast) {
      // Non-email channel (SMS) in non-last position: direct chain to next
      prevStepId = sendId;
      prevIsCondition = false;
    }
  }

  // Create a single "engaged exit" node for all conditions' "yes" branches
  if (engagedConditionIds.length > 0) {
    const exitId = `${cascadeGroupId}-exit`;
    engagedExitId = exitId;
    steps.push({
      id: exitId,
      type: "exit",
      name: "Engaged Exit",
      position: {
        x: node.position.x + 250,
        y: node.position.y + 100,
      },
      config: {
        type: "exit",
        reason: "Engaged via cascade",
      } as WorkflowStepConfig,
      cascadeGroupId,
    });

    // Connect all conditions' "yes" to the exit
    for (const condId of engagedConditionIds) {
      transitions.push({
        id: `${cascadeGroupId}-tr-${condId}-${exitId}`,
        fromStepId: condId,
        toStepId: exitId,
        condition: { branch: "yes" },
      });
    }
  }

  return {
    steps,
    transitions,
    firstStepId,
    engagedConditionIds,
    lastSendId,
    engagedExitId,
  };
}

/**
 * Convert React Flow nodes to workflow steps.
 * Expands cascade nodes into primitive steps.
 */
function nodesToSteps(nodes: WorkflowNode[]): {
  steps: WorkflowStep[];
  internalTransitions: WorkflowTransition[];
  cascadeMappings: Map<string, CascadeMapping>;
} {
  const steps: WorkflowStep[] = [];
  const internalTransitions: WorkflowTransition[] = [];
  const cascadeMappings = new Map<string, CascadeMapping>();

  for (const node of nodes) {
    if (node.type === "cascade") {
      const expanded = expandCascadeNode(node);
      steps.push(...expanded.steps);
      internalTransitions.push(...expanded.transitions);
      cascadeMappings.set(node.id, {
        firstStepId: expanded.firstStepId,
        engagedConditionIds: expanded.engagedConditionIds,
        lastSendId: expanded.lastSendId,
        engagedExitId: expanded.engagedExitId,
        allStepIds: expanded.steps.map((s) => s.id),
      });
    } else {
      steps.push({
        id: node.id,
        type: node.data.type as WorkflowStepType,
        name: node.data.name,
        position: node.position,
        config: node.data.config,
      });
    }
  }

  return { steps, internalTransitions, cascadeMappings };
}

/**
 * Convert React Flow edges to workflow transitions.
 * Resolves cascade node handles to their primitive step IDs.
 */
function edgesToTransitions(
  edges: WorkflowEdge[],
  cascadeMappings: Map<string, CascadeMapping>
): {
  transitions: WorkflowTransition[];
  /** Cascade node IDs that have externally-routed engaged edges */
  engagedExternalCascades: Set<string>;
} {
  const transitions: WorkflowTransition[] = [];
  // Track which cascade nodes have externally-routed engaged edges
  const engagedExternalTargets = new Map<string, string>();

  for (const edge of edges) {
    let fromStepId = edge.source;
    let toStepId = edge.target;
    let branch = edge.sourceHandle as string | undefined;

    // Resolve cascade target → first send step
    const targetMapping = cascadeMappings.get(edge.target);
    if (targetMapping) {
      toStepId = targetMapping.firstStepId;
    }

    // Resolve cascade source → primitive step based on handle
    const sourceMapping = cascadeMappings.get(edge.source);
    if (sourceMapping) {
      if (edge.sourceHandle === "engaged") {
        // "Engaged" means the contact opened/clicked an email in the cascade.
        // Create a transition from each engaged condition's "yes" to the target,
        // replacing the internal exit node connections.
        for (const condId of sourceMapping.engagedConditionIds) {
          transitions.push({
            id: crypto.randomUUID(),
            fromStepId: condId,
            toStepId,
            condition: { branch: "yes" },
          });
        }
        // Mark that engaged edges are externally routed so we can
        // remove the internal exit transitions later
        engagedExternalTargets.set(edge.source, toStepId);
        continue;
      }
      if (edge.sourceHandle === "exhausted") {
        fromStepId = sourceMapping.lastSendId;
        branch = undefined; // default connection from last send
      }
    }

    transitions.push({
      id: edge.id,
      fromStepId,
      toStepId,
      condition: branch
        ? {
            branch: branch as
              | "yes"
              | "no"
              | "timeout"
              | "default"
              | "opened"
              | "clicked"
              | "bounced",
          }
        : undefined,
    });
  }

  return {
    transitions,
    engagedExternalCascades: new Set(engagedExternalTargets.keys()),
  };
}

/**
 * Remove internal condition→exit transitions for cascades with external engaged edges.
 * When a user connects the "engaged" output to another node, we route directly
 * from condition "yes" branches to that node — so the internal exit transitions
 * should be removed to avoid duplicate routing.
 */
function filterInternalTransitions(
  internalTransitions: WorkflowTransition[],
  cascadeMappings: Map<string, CascadeMapping>,
  engagedExternalCascades: Set<string>
): WorkflowTransition[] {
  if (engagedExternalCascades.size === 0) return internalTransitions;

  // Collect exit step IDs for externally-routed cascades
  const exitStepIds = new Set<string>();
  for (const cascadeId of engagedExternalCascades) {
    const mapping = cascadeMappings.get(cascadeId);
    if (mapping?.engagedExitId) {
      exitStepIds.add(mapping.engagedExitId);
    }
  }

  // Remove transitions that target these exit steps
  return internalTransitions.filter((t) => !exitStepIds.has(t.toStepId));
}

/**
 * Remove internal "engaged exit" steps for cascades with external engaged edges.
 * The exit node is no longer needed when the engaged path routes externally.
 */
function filterEngagedExitSteps(
  steps: WorkflowStep[],
  cascadeMappings: Map<string, CascadeMapping>,
  engagedExternalCascades: Set<string>
): WorkflowStep[] {
  if (engagedExternalCascades.size === 0) return steps;

  const exitStepIds = new Set<string>();
  for (const cascadeId of engagedExternalCascades) {
    const mapping = cascadeMappings.get(cascadeId);
    if (mapping?.engagedExitId) {
      exitStepIds.add(mapping.engagedExitId);
    }
  }

  return steps.filter((s) => !exitStepIds.has(s.id));
}

/**
 * Get default config for a step type
 */
function getDefaultConfig(type: WorkflowStepType): WorkflowStepConfig {
  switch (type) {
    case "trigger":
      return { type: "trigger", triggerType: "event" };
    case "send_email":
      return { type: "send_email", templateId: "" };
    case "send_sms":
      return { type: "send_sms" };
    case "delay":
      return { type: "delay", amount: 1, unit: "days" };
    case "exit":
      return { type: "exit" };
    case "condition":
      return { type: "condition", field: "", operator: "equals", value: "" };
    case "webhook":
      return { type: "webhook", url: "", method: "POST" };
    case "update_contact":
      return { type: "update_contact", updates: [] };
    case "wait_for_event":
      return { type: "wait_for_event", eventName: "" };
    case "wait_for_email_engagement":
      return { type: "wait_for_email_engagement", timeoutSeconds: 259_200 }; // 3 days default
    case "subscribe_topic":
      return { type: "subscribe_topic", topicId: "", channel: "email" };
    case "unsubscribe_topic":
      return { type: "unsubscribe_topic", topicId: "", channel: "email" };
  }
}

/**
 * Get default name for a step type
 */
function getDefaultName(type: WorkflowStepType): string {
  switch (type) {
    case "trigger":
      return "Trigger";
    case "send_email":
      return "Send Email";
    case "send_sms":
      return "Send SMS";
    case "delay":
      return "Delay";
    case "exit":
      return "Exit";
    case "condition":
      return "Condition";
    case "webhook":
      return "Webhook";
    case "update_contact":
      return "Update Contact";
    case "wait_for_event":
      return "Wait for Event";
    case "wait_for_email_engagement":
      return "Email Engagement";
    case "subscribe_topic":
      return "Topic";
    case "unsubscribe_topic":
      return "Topic";
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// STORE IMPLEMENTATION
// ═══════════════════════════════════════════════════════════════════════════

export const useWorkflowStore = create<WorkflowStoreState>()(
  temporal(
    (set, get) => ({
      // Initial state
      workflow: null,
      isDirty: false,
      isSaving: false,
      nodes: [],
      edges: [],
      canvasViewport: { x: 0, y: 0, zoom: 1 },
      selectedNodeId: null,
      settingsPanelOpen: false,
      validationResult: null,

      // Actions
      setWorkflow: (workflow) => {
        const steps = workflow.steps as WorkflowStep[];
        const transitions = workflow.transitions as WorkflowTransition[];
        const nodes = stepsToNodes(steps);
        const savedViewport = workflow.canvasViewport as CanvasViewport | null;

        set({
          workflow,
          nodes,
          edges: transitionsToEdges(transitions, steps),
          canvasViewport: savedViewport ?? { x: 0, y: 0, zoom: 1 },
          isDirty: false,
          selectedNodeId: null,
        });

        // Clear undo/redo history on workflow load (fresh start)
        useWorkflowStore.temporal.getState().clear();
      },

      setNodes: (nodes) => {
        set({ nodes, isDirty: true });
      },

      setEdges: (edges) => {
        set({ edges, isDirty: true });
      },

      onNodesChange: (changes) => {
        // Only mark dirty for meaningful changes (position, remove, add)
        // Skip selection and dimension changes which happen during initialization
        const meaningfulChange = changes.some(
          (change) =>
            change.type === "position" ||
            change.type === "remove" ||
            change.type === "add"
        );

        set((state) => ({
          nodes: applyNodeChanges(changes, state.nodes),
          isDirty: meaningfulChange ? true : state.isDirty,
        }));
      },

      onEdgesChange: (changes) => {
        // Only mark dirty for meaningful changes (remove, add)
        // Skip selection changes
        const meaningfulChange = changes.some(
          (change) => change.type === "remove" || change.type === "add"
        );

        set((state) => ({
          edges: applyEdgeChanges(changes, state.edges),
          isDirty: meaningfulChange ? true : state.isDirty,
        }));
      },

      onConnect: (connection) => {
        set((state) => ({
          edges: addEdge(
            {
              ...connection,
              id: crypto.randomUUID(),
            },
            state.edges
          ),
          isDirty: true,
        }));
      },

      onReconnect: (oldEdge, newConnection) => {
        set((state) => ({
          edges: reconnectEdge(oldEdge, newConnection, state.edges),
          isDirty: true,
        }));
      },

      addNode: (type, position, config) => {
        // Cascade: create a single self-contained node
        if (type === "cascade") {
          const id = crypto.randomUUID();
          const newNode: WorkflowNode = {
            id,
            type: "cascade",
            position,
            data: {
              stepId: id,
              type: "cascade",
              name: "Cascade",
              config: { type: "exit" } as WorkflowStepConfig, // placeholder
              isValid: true,
              cascadeChannels: [
                {
                  id: crypto.randomUUID(),
                  type: "email",
                  templateId: "",
                  engagement: "opened",
                  waitDuration: 259_200, // 3 days
                },
                { id: crypto.randomUUID(), type: "sms", body: "" },
              ],
            },
          };

          set((state) => ({
            nodes: [...state.nodes, newNode],
            isDirty: true,
            selectedNodeId: id,
          }));

          return id;
        }

        // Normal node addition
        const id = crypto.randomUUID();
        const defaultConfig = getDefaultConfig(type);
        const mergedConfig = config
          ? { ...defaultConfig, ...config }
          : defaultConfig;

        const newNode: WorkflowNode = {
          id,
          type,
          position,
          data: {
            stepId: id,
            type,
            name: getDefaultName(type),
            config: mergedConfig as WorkflowStepConfig,
            isValid: true,
          },
        };

        set((state) => ({
          nodes: [...state.nodes, newNode],
          isDirty: true,
          selectedNodeId: id,
        }));

        return id;
      },

      updateNodeConfig: (nodeId, config) => {
        set((state) => ({
          nodes: state.nodes.map((node) =>
            node.id === nodeId
              ? {
                  ...node,
                  data: {
                    ...node.data,
                    config: {
                      ...node.data.config,
                      ...config,
                    } as WorkflowStepConfig,
                  },
                }
              : node
          ),
          isDirty: true,
        }));
      },

      updateNodeName: (nodeId, name) => {
        set((state) => ({
          nodes: state.nodes.map((node) =>
            node.id === nodeId
              ? {
                  ...node,
                  data: {
                    ...node.data,
                    name,
                  },
                }
              : node
          ),
          isDirty: true,
        }));
      },

      updateCascadeChannels: (nodeId, channels) => {
        set((state) => ({
          nodes: state.nodes.map((node) =>
            node.id === nodeId
              ? {
                  ...node,
                  data: {
                    ...node.data,
                    cascadeChannels: channels,
                  },
                }
              : node
          ),
          isDirty: true,
        }));
      },

      deleteNode: (nodeId) => {
        set((state) => ({
          nodes: state.nodes.filter((node) => node.id !== nodeId),
          edges: state.edges.filter(
            (edge) => edge.source !== nodeId && edge.target !== nodeId
          ),
          selectedNodeId:
            state.selectedNodeId === nodeId ? null : state.selectedNodeId,
          isDirty: true,
        }));
      },

      selectNode: (nodeId) => {
        set({ selectedNodeId: nodeId });
      },

      toggleSettingsPanel: () => {
        set((state) => ({ settingsPanelOpen: !state.settingsPanelOpen }));
      },

      setSettingsPanelOpen: (open) => {
        set({ settingsPanelOpen: open });
      },

      setCanvasViewport: (viewport) => {
        set({ canvasViewport: viewport });
      },

      updateWorkflowSettings: (settings) => {
        set((state) => {
          if (!state.workflow) {
            return state;
          }

          return {
            workflow: {
              ...state.workflow,
              ...settings,
            },
            isDirty: true,
          };
        });
      },

      getWorkflowDefinition: () => {
        const state = get();
        const { steps, internalTransitions, cascadeMappings } = nodesToSteps(
          state.nodes
        );
        const { transitions: externalTransitions, engagedExternalCascades } =
          edgesToTransitions(state.edges, cascadeMappings);

        // Filter out internal condition→exit transitions for cascades that
        // have externally-routed engaged edges (the exit node is replaced)
        const filteredInternal = filterInternalTransitions(
          internalTransitions,
          cascadeMappings,
          engagedExternalCascades
        );

        return {
          steps: filterEngagedExitSteps(
            steps,
            cascadeMappings,
            engagedExternalCascades
          ),
          transitions: [...filteredInternal, ...externalTransitions],
          canvasViewport: state.canvasViewport,
        };
      },

      setIsSaving: (isSaving) => {
        set({ isSaving });
      },

      markClean: () => {
        set({ isDirty: false });
      },

      updateWorkflowAfterSave: (workflow) => {
        // Only update workflow metadata, don't touch nodes/edges
        // This prevents React Flow from firing change events that would set isDirty=true
        set({ workflow, isDirty: false });
      },

      runValidation: () => {
        const state = get();
        const { steps, internalTransitions, cascadeMappings } = nodesToSteps(
          state.nodes
        );
        const { transitions: externalTransitions } = edgesToTransitions(
          state.edges,
          cascadeMappings
        );
        const result = validateAutomation(steps, [
          ...internalTransitions,
          ...externalTransitions,
        ]);

        // Map validation errors from primitive cascade step IDs back to cascade node IDs
        const mappedResult = mapCascadeValidationErrors(
          result,
          cascadeMappings
        );

        // Validate cascade channel configs (template/body required, wait durations, etc.)
        for (const node of state.nodes) {
          if (node.type === "cascade" && node.data.cascadeChannels) {
            const cascadeErrors = validateCascadeChannels(
              node.id,
              node.data.cascadeChannels
            );
            mappedResult.errors.push(...cascadeErrors);
            for (const error of cascadeErrors) {
              if (error.nodeId) {
                const existing =
                  mappedResult.errorsByNodeId.get(error.nodeId) || [];
                existing.push(error);
                mappedResult.errorsByNodeId.set(error.nodeId, existing);
              }
            }
            if (cascadeErrors.some((e) => e.severity === "error")) {
              mappedResult.isValid = false;
            }
          }
        }

        // Only update validationResult, don't touch nodes to avoid infinite loops
        set({ validationResult: mappedResult });
        return mappedResult;
      },

      applyAIFlow: (steps, transitions) => {
        // Convert AI-generated steps and transitions to React Flow nodes and edges
        const nodes = stepsToNodes(steps);
        const edges = transitionsToEdges(transitions, steps);

        set({
          nodes,
          edges,
          isDirty: true,
          selectedNodeId: null,
        });

        // Run validation on the new flow
        get().runValidation();
      },
    }),
    {
      partialize: (state) => ({
        nodes: state.nodes,
        edges: state.edges,
      }),
      equality: (pastState, currentState) =>
        pastState.nodes === currentState.nodes &&
        pastState.edges === currentState.edges,
      limit: 50,
    }
  )
);

/**
 * Map validation errors from primitive cascade step IDs back to
 * the cascade node ID so they show up on the cascade node.
 */
function mapCascadeValidationErrors(
  result: ValidationResult,
  cascadeMappings: Map<string, CascadeMapping>
): ValidationResult {
  if (cascadeMappings.size === 0) return result;

  // Build reverse map: primitive step ID → cascade node ID
  const primitiveToGroup = new Map<string, string>();
  for (const [cascadeNodeId, mapping] of cascadeMappings) {
    for (const stepId of mapping.allStepIds) {
      primitiveToGroup.set(stepId, cascadeNodeId);
    }
  }

  // Remap errors from primitive step IDs to cascade node IDs
  const mappedErrors = result.errors.map((error) => {
    if (error.nodeId && primitiveToGroup.has(error.nodeId)) {
      return { ...error, nodeId: primitiveToGroup.get(error.nodeId)! };
    }
    return error;
  });

  // Rebuild errorsByNodeId
  const errorsByNodeId = new Map<string, ValidationError[]>();
  for (const error of mappedErrors) {
    if (error.nodeId) {
      const existing = errorsByNodeId.get(error.nodeId) || [];
      existing.push(error);
      errorsByNodeId.set(error.nodeId, existing);
    }
  }

  return {
    isValid: mappedErrors.every((e) => e.severity !== "error"),
    errors: mappedErrors,
    errorsByNodeId,
  };
}

// Selector hooks for common state slices
// Uses single selector to avoid double subscription and unnecessary re-renders
export const useSelectedNode = () =>
  useWorkflowStore((state) =>
    state.selectedNodeId
      ? state.nodes.find((node) => node.id === state.selectedNodeId)
      : null
  );

export const useIsDirty = () => useWorkflowStore((state) => state.isDirty);
export const useIsSaving = () => useWorkflowStore((state) => state.isSaving);
// Derived selector for node count - avoids subscribing to full nodes array
export const useNodeCount = () =>
  useWorkflowStore((state) => state.nodes.length);
export const useSettingsPanelOpen = () =>
  useWorkflowStore((state) => state.settingsPanelOpen);
export const useValidationResult = () =>
  useWorkflowStore((state) => state.validationResult);

export const useNodeValidation = (nodeId: string) => {
  const validationResult = useWorkflowStore((state) => state.validationResult);
  if (!validationResult) {
    return { isValid: true, errorMessage: undefined };
  }

  const errors = validationResult.errorsByNodeId.get(nodeId) || [];
  const hasError = errors.some((e) => e.severity === "error");
  const errorMessage = errors
    .filter((e) => e.severity === "error")
    .map((e) => e.message)
    .join(", ");

  return { isValid: !hasError, errorMessage: errorMessage || undefined };
};

// ═══════════════════════════════════════════════════════════════════════════
// UNDO/REDO
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Handle undo/redo keyboard events.
 * Accepts a plain key descriptor (not DOM-specific) for testability.
 * Wire this to `onKeyDown` in the canvas component.
 */
export function handleUndoRedo(event: {
  key: string;
  metaKey: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
}) {
  const mod = event.metaKey || event.ctrlKey;
  if (!mod) return;

  if (event.key === "z" && event.shiftKey) {
    useWorkflowStore.temporal.getState().redo();
  } else if (event.key === "z") {
    useWorkflowStore.temporal.getState().undo();
  } else if (event.key === "y") {
    useWorkflowStore.temporal.getState().redo();
  }
}

export const useCanUndo = () =>
  useStore(useWorkflowStore.temporal, (state) => state.pastStates.length > 0);

export const useCanRedo = () =>
  useStore(useWorkflowStore.temporal, (state) => state.futureStates.length > 0);

// Re-export validation types for convenience
export type {
  ValidationError,
  ValidationResult,
} from "@/lib/automation-validation";
