/**
 * Regenerates src/config/page-dates.ts — the per-route `lastModified` the
 * sitemap serves.
 *
 * Why a committed file rather than computing this during the build:
 *
 *  - File mtime is useless on Vercel. The build starts from a fresh git
 *    checkout, so every file carries the clone timestamp and all 138 URLs
 *    claimed the same `lastmod` on every deploy. That is what this replaces.
 *  - `git log` during the build is no better: Vercel shallow-clones, so most
 *    pages have no commit in the history the build can see.
 *  - Turbo can restore a cached .next and skip the build entirely, so anything
 *    computed at build time is not guaranteed to run at all.
 *
 * Committing the dates sidesteps all three. Run this before committing a
 * content change; sitemap.test.ts fails when a route's files have moved on
 * without it.
 *
 *   pnpm sitemap:dates
 */

import { execFileSync } from "node:child_process";
import { globSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import {
  ownerRouteFor,
  routeDirsByDepth,
  routeForPageFile,
} from "../src/lib/page-dates";

/** A `git log --format=%cI` line, as opposed to a file path. */
const ISO_DATE_LINE = /^\d{4}-\d{2}-\d{2}T/;

/** biome's default; entries wider than this get their value on its own line. */
const FORMATTER_LINE_WIDTH = 80;

const websiteRoot = resolve(import.meta.dirname, "..");
const repoRoot = resolve(websiteRoot, "..", "..");
const appDir = join(websiteRoot, "src/app");
const appDirFromRepo = relative(repoRoot, appDir);

function git(args: string[]): string {
  return execFileSync("git", args, {
    cwd: repoRoot,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
}

/** Last commit date for every tracked file under src/app, in one git pass. */
function lastCommitByFile(): Map<string, string> {
  const log = git(["log", "--format=%cI", "--name-only", "--", appDirFromRepo]);
  const dates = new Map<string, string>();
  let commitDate = "";
  for (const line of log.split("\n")) {
    if (line === "") {
      continue;
    }
    if (ISO_DATE_LINE.test(line)) {
      commitDate = line;
      continue;
    }
    // Files are listed newest commit first, so the first sighting wins.
    if (!dates.has(line)) {
      dates.set(line, commitDate);
    }
  }
  return dates;
}

/** src/app-relative paths with uncommitted changes, including untracked. */
function dirtyFiles(): Set<string> {
  const status = git(["status", "--porcelain", "--", appDirFromRepo]);
  const dirty = new Set<string>();
  for (const line of status.split("\n")) {
    if (line === "") {
      continue;
    }
    // "XY path" and, for renames, "XY old -> new".
    const path = line.slice(3).split(" -> ").pop();
    if (path !== undefined) {
      dirty.add(
        relative(appDir, resolve(repoRoot, path.replace(/^"|"$/g, "")))
      );
    }
  }
  return dirty;
}

function main(): void {
  const pageFiles = globSync("**/page.tsx", { cwd: appDir });
  const routeDirs = routeDirsByDepth(pageFiles);

  const dates = new Map<string, string>();
  const record = (route: string, date: string) => {
    const current = dates.get(route);
    if (current === undefined || date > current) {
      dates.set(route, date);
    }
  };

  for (const [repoPath, date] of lastCommitByFile()) {
    const owner = ownerRouteFor(
      relative(appDir, resolve(repoRoot, repoPath)),
      routeDirs
    );
    if (owner !== undefined) {
      record(owner, date);
    }
  }

  // Uncommitted work is about to become the newest commit — record it as now so
  // that generating and committing in one go lands the right date, rather than
  // the date of the previous change to the same page.
  const now = new Date().toISOString();
  for (const appRelative of dirtyFiles()) {
    const owner = ownerRouteFor(appRelative, routeDirs);
    if (owner !== undefined) {
      record(owner, now);
    }
  }

  const routes = pageFiles
    .map(routeForPageFile)
    .sort((a, b) => a.localeCompare(b));
  // Emit what the formatter would produce, so a regenerate never fails lint:
  // biome wraps the value onto its own line once the pair exceeds 80 columns.
  const entries = routes.map((route) => {
    const oneLine = `  "${route}": "${dates.get(route) ?? now}",`;
    if (oneLine.length <= FORMATTER_LINE_WIDTH) {
      return oneLine;
    }
    return `  "${route}":\n    "${dates.get(route) ?? now}",`;
  });

  const file = `// Generated by scripts/generate-page-dates.ts — do not edit by hand.
// Run \`pnpm sitemap:dates\` after changing page content, then commit both.
//
// The last commit date of each route's own files (its page.tsx, its
// page-content.tsx, and any components private to it). Serves the sitemap's
// <lastmod>, which cannot be derived at build time: see the script header.

export const PAGE_DATES: Record<string, string> = {
${entries.join("\n")}
};
`;

  writeFileSync(join(websiteRoot, "src/config/page-dates.ts"), file);
  process.stdout.write(
    `Wrote ${routes.length} route dates to src/config/page-dates.ts\n`
  );
}

main();
