import { globSync } from "node:fs";
import { join } from "node:path";
import type { MetadataRoute } from "next";
import { PAGE_DATES } from "@/config/page-dates";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://wraps.dev";
  const appDir = join(process.cwd(), "src/app");

  const pages = globSync("**/page.tsx", { cwd: appDir });

  const routes = pages
    .map((file) => {
      const route = file
        .replace(/\/page\.tsx$/, "")
        .replace(/page\.tsx$/, "")
        .replace(/\([^)]+\)\/?/g, ""); // strip route groups like (auth)/
      return `/${route}`.replace(/\/$/, "") || "/";
    })
    .filter((path) => path !== "/sitemap")
    .sort((a, b) => a.localeCompare(b));

  return routes.map((path) => ({
    url: `${baseUrl}${path === "/" ? "" : path}`,
    // Committed in src/config/page-dates.ts, regenerated by `pnpm sitemap:dates`.
    // Neither of the obvious alternatives survives contact with the deploy: file
    // mtime is the git-checkout time on Vercel (all 138 URLs shared one
    // timestamp, so every deploy claimed the whole site had changed), and
    // `git log` during the build sees only Vercel's shallow clone. A route with
    // no recorded date sends no <lastmod> rather than a wrong one.
    lastModified: dateFor(path),
    changeFrequency: path === "/" ? "daily" : "weekly",
    priority:
      path === "/"
        ? 1
        : path.startsWith("/tools")
          ? 0.9
          : path.startsWith("/docs") ||
              path.startsWith("/compare") ||
              path.startsWith("/alternatives")
            ? 0.8
            : 0.7,
  }));
}

function dateFor(path: string): Date | undefined {
  const recorded = PAGE_DATES[path];
  return recorded === undefined ? undefined : new Date(recorded);
}
